version: "3"

services:
      
      mysql:
          container_name: mysql-container
          image: mysql:8.0
          environment:
                - MYSQL_ROOT_PASSWORD=sachin
                - MYSQL_DATABASE=test_db
          networks:
              - myNet 
          volumes:
              - mysql_data:/var/lib/mysql      
          healthcheck:
                test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
                interval: 10s
                retries: 5
                start_period: 20s
                timeout: 5s      

      backend:
          container_name: backend-image
          build: ./
          ports:
            - 4700:4700
          networks:
              - myNet  
          volumes:
              - ./:/app 
          depends_on:
              - mysql
         
 
volumes:
    mysql_data:
networks:
    myNet:
      external: true    